spring:
  datasource:
    url: jdbc:sqlserver://shawnsproject.database.windows.net:1433;database=passion;user=shawn@shawnsproject;password=password123!;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: shawn
    password: password123!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191