#version: '3'
#services:
#  app:
#    build: .
#    ports:
#      - 8080:8080
#    depends_on:
#      - db
#  db:
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: passion
#    volumes:
#      - db-data:/var/lib/mysql
#volumes:
#  db-data:




